//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM_Database_First_CPHAirport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public string iATA { get; set; }
        public string name { get; set; }
    
        public virtual FlightRoute FlightRoute { get; set; }
    }
}
